In [1]:
#10
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
import numpy as np

# AND gate data
X_and = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_and = np.array([0, 0, 0, 1])

# XOR gate data
X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_xor = np.array([0, 1, 1, 0])

# Feature Scaling
scaler = StandardScaler()

# Scale AND data
X_and_scaled = scaler.fit_transform(X_and)

# Scale XOR data
X_xor_scaled = scaler.fit_transform(X_xor)

# Train and predict for AND gate
clf_and = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
clf_and.fit(X_and_scaled, y_and)
predictions_and = clf_and.predict(X_and_scaled)
print("AND Predictions:", predictions_and)

# Train and predict for XOR gate
clf_xor = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
clf_xor.fit(X_xor_scaled, y_xor)
predictions_xor = clf_xor.predict(X_xor_scaled)
print("XOR Predictions:", predictions_xor)


AND Predictions: [0 0 0 1]
XOR Predictions: [0 1 1 0]


In [7]:
#11
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load the dataset
data_path = "embeddingsdata.xlsx"
data = pd.read_excel(data_path)

# Convert non-numeric columns to numeric using LabelEncoder
le = LabelEncoder()

for column in data.columns:
    if data[column].dtype == type(object):
        data[column] = le.fit_transform(data[column])

# Define inputs (features) and target
X = data.drop('Label', axis=1)
y = data['Label']

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the MLP classifier
clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(5, 2), max_iter=10000, random_state=1)
clf.fit(X_train_scaled, y_train)

# Predict using the trained model
predictions = clf.predict(X_test_scaled)

# Print the accuracy
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, predictions)
print("Confusion Matrix:")
print(conf_matrix)



Accuracy: 38.89%
Confusion Matrix:
[[27  8 22  0  0  8  3  0  0  0  0]
 [11 34  2  0  0  2  0  0  1  2  0]
 [ 6  2  6  0  0  8  0  0  0  1  0]
 [ 0  1  1  0  0  0  0  0  1  0  0]
 [ 3  0  2  0  0  0  0  0  0  0  0]
 [ 5  3  2  0  0  0  0  0  0  2  0]
 [ 3  0  0  0  0  0  1  0  0  0  0]
 [ 1  1  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0]
 [ 3  0  1  0  0  0  0  0  0  2  0]
 [ 2  0  0  0  0  2  0  0  0  0  0]]
